---
title: "02_Prepare_Metabolomics_Data"
author: "Yu Zhang"
output:
  md_document:
    variant: markdown_github
  html_document: default
---

```{r Load packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


```{r, warning=FALSE}
batch1_metab_sheet_name <- "data"
batch2_metab_sheet_name <- "batch2_batchnormalized_v1"
batch1_sample_info_sheet_name <- "sample.info"
batch2_sample_info_sheet_name <- "sample.info_batch2_v1"
metabolites_info_sheet_name <- "metabolites.info"
```

```{r, warning=FALSE}
metab_vals_batch1 <- read_excel("2batch_combined_data_V1_only.xlsx", sheet = batch1_metab_sheet_name)
metab_vals_batch2 <- read_excel("batch2_data.xlsx", sheet = batch2_metab_sheet_name)

metab_vals_batch2 <- metab_vals_batch2[, colnames(metab_vals_batch1)]

sample_info_batch1 <- read_excel("2batch_combined_data_V1_only.xlsx", sheet = batch1_sample_info_sheet_name)
sample_info_batch2 <- read_excel("batch2_data.xlsx", sheet = batch2_sample_info_sheet_name)

metab_vals_batch1 <- merge(metab_vals_batch1, 
                           sample_info_batch1[,c("PARENT_SAMPLE_NAME", "SOL_ID")], 
                           by = "PARENT_SAMPLE_NAME")

metab_vals_batch2 <- merge(metab_vals_batch2, 
                           sample_info_batch2[,c("PARENT_SAMPLE_NAME", "SOL_ID")], 
                           by = "PARENT_SAMPLE_NAME")

set.seed(1997)
random_index_b1 <- data.frame(index = 1:nrow(metab_vals_batch1 ), SOL_ID = metab_vals_batch1$SOL_ID)
for (id in unique(random_index_b1$SOL_ID)){
  row_inds <- which(random_index_b1$SOL_ID == id)
  if (length(row_inds) == 1) next
  selected_ind <- sample(row_inds, 1)
  random_index_b1 <- random_index_b1[-setdiff(row_inds, selected_ind),]
}
metab_vals_batch1 <- metab_vals_batch1[random_index_b1$index,]



random_index_b2 <- data.frame(index = 1:nrow(metab_vals_batch2 ), SOL_ID = metab_vals_batch2$SOL_ID)
for (id in unique(random_index_b2$SOL_ID)){
  row_inds <- which(random_index_b2$SOL_ID == id)
  if (length(row_inds) == 1) next
  selected_ind <- sample(row_inds, 1)
  random_index_b2 <- random_index_b2[-setdiff(row_inds, selected_ind),]
}
metab_vals_batch2 <- metab_vals_batch2[random_index_b2$index,]

metab_vals_batch2 <- metab_vals_batch2[-which(is.element(metab_vals_batch2$SOL_ID, metab_vals_batch1$SOL_ID)),]
```

```{r, warning=FALSE}
miss_prop <- 0.25
all(colnames(metab_vals_batch1) == colnames(metab_vals_batch2))
missing_prop <- data.frame(CHEM_ID = colnames(metab_vals_batch1)[-1], 
                           missing_prop_batch1 = NA, 
                           missing_prop_batch2 = NA)

missing_prop$missing_prop_batch1 <- apply(metab_vals_batch1, 2, function(x){mean(is.na(x))})[-1]
missing_prop$missing_prop_batch2 <- apply(metab_vals_batch2, 2, function(x){mean(is.na(x))})[-1]

inds_acceptable <- which(missing_prop$missing_prop_batch1 < miss_prop  & missing_prop$missing_prop_batch2 < miss_prop )
CHEM_ID_keep <- missing_prop$CHEM_ID[inds_acceptable]
CHEM_ID_keep <- setdiff(CHEM_ID_keep, "SOL_ID")

metab_vals_batch1 <- metab_vals_batch1[,c("SOL_ID", CHEM_ID_keep)]
metab_vals_batch2 <- metab_vals_batch2[,c("SOL_ID", CHEM_ID_keep)]

metab_mins_batch1 <- apply(metab_vals_batch1[,CHEM_ID_keep], 2, function(x){min(x, na.rm = TRUE)})
metab_mins_batch2 <- apply(metab_vals_batch2[,CHEM_ID_keep], 2, function(x){min(x, na.rm = TRUE)})

for (i in 1:length(CHEM_ID_keep)){
  cur_chem <- CHEM_ID_keep[i]
  batch1_mis_inds_cur_chem <- which(is.na(metab_vals_batch1[,cur_chem]))
  if (length(batch1_mis_inds_cur_chem) > 0){
    metab_vals_batch1[batch1_mis_inds_cur_chem,cur_chem] <- metab_mins_batch1[cur_chem]/2
  }
 
  batch2_mis_inds_cur_chem <- which(is.na(metab_vals_batch2[,cur_chem]))
  if (length(batch2_mis_inds_cur_chem) > 0){
    metab_vals_batch2[batch2_mis_inds_cur_chem,cur_chem] <- metab_mins_batch2[cur_chem]/2
  } 
  
}

#saveRDS(metab_vals_batch1, file = "Processed_metab_b1_updated.RDS")

#saveRDS(metab_vals_batch2, file = "Processed_metab_b2_updated.RDS")
```





































